# Generated by Django 3.2 on 2021-04-26 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_of_release',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
