# Generated by Django 3.2 on 2021-04-26 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210327_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
